[package]
name = "aoc_harness"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
proc-macro2 = "1.0.32"
quote = "1.0.10"
syn = "1.0.81"
structopt = "0.3"
time = "0.3.5"
itertools = "0.10.1"
ureq = "2.3.1"
dotenv = "0.15.0"
aoc_harness_macros = { path = "libs/macros"}