name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      working-directory: aoc2021
      run: cargo build --verbose
    - name: Run tests
      working-directory: aoc2021
      run: cargo test --verbose --bin all --lib
    - name: Run for score
      working-directory: aoc2021      
      run: cargo run --bin all
