name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: Swatinem/rust-cache@v1
    - name: Build
      run: cargo build
    - name: Run tests
      run: cargo test --bin all --lib
    - name: Check clippy
      run: cargo clippy
    - name: Run for score (2019)
      run: cargo run --bin all --release -p aoc2019
    - name: Run for score (2021)
      run: cargo run --bin all --release -p aoc2021
    - name: Check formatting
      run: cargo fmt --all -- --check

