name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: Swatinem/rust-cache@v1
      with: 
        working-directory: aoc2021
    # - uses: actions/cache@v2
    #   with:
    #     path: |
    #       ~/.cargo/bin/
    #       ~/.cargo/registry/index/
    #       ~/.cargo/registry/cache/
    #       ~/.cargo/git/db/
    #       aoc2021/target/
    #     key: ${{ runner.os }}-cargo-${{ hashFiles('aoc2021/Cargo.lock')}}
    - name: Build
      working-directory: aoc2021
      run: cargo build --verbose --release
    - name: Run tests
      working-directory: aoc2021
      run: cargo test --verbose --bin all --lib --release
    - name: Run for score
      working-directory: aoc2021      
      run: cargo run --bin all --release
