name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: Swatinem/rust-cache@v2
    - name: Build
      run: cargo build --release
    - name: Run tests
      run: cargo test --lib --release
    - name: Check clippy
      run: cargo clippy
    - name: Run for score
      run: cargo run --release --bin aoc
    - name: Check formatting
      run: cargo fmt --all -- --check

