name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: Swatinem/rust-cache@v1
      with: 
        working-directory: aoc2021
    - name: Build
      run: cargo build
    - name: Run tests
      run: cargo test --bin all --lib --release
    - name: Run for score
      run: cargo run --bin all --release
    - name: Check clippy
      run: cargo clippy --release

